// List of all 76 barangays in Tarlac City
export const TARLAC_BARANGAYS = [
    'Aguso',
    'Alvindia Segundo',
    'Amucao',
    'Armenia',
    'Asturias',
    'Atioc',
    'Balanti',
    'Balete',
    'Balibago I',
    'Balibago II',
    'Balingcanaway',
    'Banaba',
    'Bantog',
    'Barangay 1',
    'Barangay 2',
    'Barangay 3',
    'Barangay 4',
    'Barangay 5',
    'Barangay 6',
    'Barangay 7',
    'Barangay 8',
    'Barangay 9',
    'Barangay 10',
    'Barangay 11',
    'Barangay 12',
    'Barangay 13',
    'Barangay 14',
    'Barangay 15',
    'Barangay 16',
    'Barangay 17',
    'Barangay 18',
    'Barangay 19',
    'Barangay 20',
    'Barangay 21',
    'Batang-batang',
    'Binauganan',
    'Burot',
    'Calingcuan',
    'Caluluan',
    'Camiling',
    'Care',
    'Coral-islac',
    'Dangla',
    'Del Rosario',
    'Dimasalasa',
    'Salapungan',
    'San Vicente',
    'Señor-isen',
    'Sulao',
    'Sinilian',
    'Tariji',
    'Tarlac (Pob.)',
    'Tibag',
    'Tilapayong',
    'Upper Orutu',
    'Villa Roselda',
    'Villa Rosa',
    'Victoria',
    'Vista Hermosa',
    'La Fuente',
    'Lapaz',
    'Las Vegas',
    'Lawacambao',
    'Ligtasan',
    'Lourdes',
    'Malacampa',
    'Maliwalo',
    'Mapalacsiao',
    'Mapalad',
    'Matatalaib',
    'Pacac',
    'Palanan',
    'Palpucal',
    'Panalin',
    'Pando',
    'Parayno',
    'Poblacion',
    'San Juan Bautista',
    'San Miguel',
    'San Nicolas',
    'San Rafael',
    'San Sebastian',
] as const

export type Barangay = typeof TARLAC_BARANGAYS[number]

